In [10]:
import pandas as pd

In [11]:
df = pd.read_csv("data/to_analysis.csv")
df

,contrato_id,total_success_dsp5,total_success_dsp10,total_success_dsp15,total_success_dsp30,total_success_dsp60,total_success_dsp90,prop_success_dsp5,prop_success_dsp10,prop_success_dsp15,...,"('qtd_transacoes', 'mean')","('qtd_transacoes', 'min')","('qtd_transacoes', 'max')","('qtd_transacoes', 'median')","('qtd_transacoes', 'sum')","('vlr_tpv', 'mean')","('vlr_tpv', 'min')","('vlr_tpv', 'max')","('vlr_tpv', 'median')","('vlr_tpv', 'sum')"
0,000180509391a5ac66ff83cae603ffb8,1,1,0,0,0,0,0.000000,1.000000,NaN,...,12.357995,1.0,42.0,10.0,5178.0,443.126253,6.00,1426.50,340.00,185669.90
1,000c35a61297edadc2842f6d5b4028e1,4,1,1,1,1,1,0.750000,0.000000,0.000000,...,15.026616,1.0,66.0,11.0,3952.0,580.125856,3.50,14033.50,400.50,152573.10
2,bcd244d93204f40ca32f55fa2b06ca1f,2,2,2,2,2,2,0.000000,0.000000,0.000000,...,15.026616,1.0,66.0,11.0,3952.0,580.125856,3.50,14033.50,400.50,152573.10
3,000dcdc93a545ee45a1aee85ef85c34a,11,7,6,2,1,1,0.363636,0.285714,0.666667,...,1.500000,1.0,5.0,1.0,45.0,2538.660000,1.00,23000.00,1550.00,76159.80
4,0014cccd47b66a47af4e62c4dcbe95f1,3,1,1,1,0,0,0.666667,0.000000,0.000000,...,5.033784,1.0,13.0,5.0,2235.0,196.886892,2.00,652.90,173.90,87417.78
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12197,fff4bf15d5b48a5c1bda798ea77290d1,1,0,0,0,0,0,1.000000,NaN,NaN,...,1.556213,1.0,5.0,1.0,263.0,550.142012,5.00,10055.00,148.00,92974.00
12198,fff6edc99168d63a10ea51a7f808ff38,3,1,0,0,0,0,0.666667,1.000000,NaN,...,1.991489,1.0,7.0,2.0,468.0,947.456596,2.00,6198.00,592.00,222652.30
12199,fffb0d6ec51d163ca8c69900f748d61b,5,3,2,0,0,0,0.200000,0.333333,1.000000,...,46.116992,2.0,199.0,43.0,16556.0,1870.555153,57.60,12323.61,1635.85,671529.30
12200,fffb47b9ce3835c85513ef5b19165f6e,1,1,1,1,0,0,0.000000,0.000000,0.000000,...,45.919118,8.0,287.0,39.0,24980.0,1765.287188,163.00,18548.58,1235.83,960316.23
12201,fffc9af28349e8ded3af8e2dcbf9c3bc,0,0,0,0,0,0,NaN,NaN,NaN,...,4.241463,1.0,16.0,4.0,1739.0,735.773024,0.01,4375.00,539.00,301666.94

# Score vs total de sucesso vs total de comunicação

In [12]:
df.columns

Index(['contrato_id', 'total_success_dsp5', 'total_success_dsp10',
       'total_success_dsp15', 'total_success_dsp30', 'total_success_dsp60',
       'total_success_dsp90', 'prop_success_dsp5', 'prop_success_dsp10',
       'prop_success_dsp15', 'prop_success_dsp30', 'prop_success_dsp60',
       'prop_success_dsp90', 'total_success_dspp15', 'total_success_dspp30',
       'total_success_dspp45', 'prop_success_dspp15', 'prop_success_dspp30',
       'prop_success_dspp45', 'score_dsp', 'score_dspp', 'get_entregue',
       'get_lido', 'get_nao_entregue', 'vlr_saldo_devedor_esperado',
       'nr_documento', 'tipo_empresa', 'cidade', 'estado', 'subsegmento',
       'segmento', '('qtd_transacoes', 'mean')', '('qtd_transacoes', 'min')',
       '('qtd_transacoes', 'max')', '('qtd_transacoes', 'median')',
       '('qtd_transacoes', 'sum')', '('vlr_tpv', 'mean')',
       '('vlr_tpv', 'min')', '('vlr_tpv', 'max')', '('vlr_tpv', 'median')',
       '('vlr_tpv', 'sum')'],
      dtype='object')

In [19]:
totals = [column for column in df.columns if column.startswith("total_")]

score_success_action = df[
    [
        "nr_documento",
        "score_dsp",
        *totals,
        "get_entregue",
        "get_lido",
        "get_nao_entregue",
    ]
]

In [20]:
score_success_action.sort_values("score_dsp", ascending=False)

,nr_documento,score_dsp,total_success_dsp5,total_success_dsp10,total_success_dsp15,total_success_dsp30,total_success_dsp60,total_success_dsp90,total_success_dspp15,total_success_dspp30,total_success_dspp45,get_entregue,get_lido,get_nao_entregue
6117,67853c8b604c9b7b99960b69079cfdec,1.0,1,0,0,0,0,0,1,1,0,1,0,5
9203,d28fb90a87838fb5de2206642c35b5f1,1.0,3,0,0,0,0,0,3,0,0,4,4,4
9228,01d6b0c45f3608d2d0fb8b7539c8769d,1.0,2,0,0,0,0,0,3,1,0,6,2,4
9223,a414329608e8e033661ad6657ad5b2d0,1.0,1,0,0,0,0,0,1,0,0,0,0,4
3585,3695e78a5145478e13dcc55cdf1e9971,1.0,1,0,0,0,0,0,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12134,5b34dd71c6df23b4ec3e60f659dc6735,NaN,0,0,0,0,0,0,2,2,1,3,3,4
12137,762f1b9d1029c64ec82e3bb1edaad2f5,NaN,0,0,0,0,0,0,5,1,0,3,1,7
12158,af8a40489eeef72513dd1a0f67483c5c,NaN,0,0,0,0,0,0,1,1,1,2,2,2
12159,e33a444620bc517821b8b2a592490800,NaN,0,0,0,0,0,0,1,0,0,1,0,1
12201,cee34a02820f1120a5046f416a3e0967,NaN,0,0,0,0,0,0,1,0,0,1,0,1

In [21]:
comunicados = pd.read_csv("data/portfolio_comunicados.csv")
comunicados

,contrato_id,dt_ref_portfolio,data_acao,tipo_acao,acao,status
0,0d823ddff1839eb938dccc68586ae365,2021-01-16,2021-01-18,HSM,campanhaobservacao,LIDO
1,c2f8a21671dbaeaa4157e03682c639e1,2021-05-22,2021-05-24,HSM,campanhaobservacao,ENTREGUE
2,e19a222c233d46ff4984489c13aa1b98,2020-09-15,2020-09-15,HSM,campanhaobservacao,NAO ENTREGUE
3,c24fc7630fe5b89928ba9478c2cdd9b2,2021-07-20,2021-07-20,HSM,campanhaobservacao,NAO ENTREGUE
4,0abe9c2f21e941f2bd3b086277e33ebc,2020-12-26,2020-12-28,HSM,campanhaobservacao,ENTREGUE
...,...,...,...,...,...,...
403735,c7dc25f386144912b90500ffd45e71c5,2020-10-19,2020-10-19,HSM,campanhaboletoquitado,NAO ENTREGUE
403736,76c9917af4fa0810bd2e5638523a1a30,2020-06-19,2020-06-19,HSM,campanhaboletoquitado,LIDO
403737,724407e5260f93c0e3ea385564bdc731,2021-06-28,2021-06-28,HSM,campanhaboletoquitado,NAO ENTREGUE
403738,42b5d6594f79ee300ce0966c894b04c5,2021-09-26,2021-09-28,HSM,campanhaboletoquitado,NAO ENTREGUE
403739,83ead8d8ac5cf8e60759058ec3588bdb,2021-02-07,2021-02-09,HSM,campanhaboletoquitado,NAO ENTREGUE

In [25]:
comunicados[comunicados["contrato_id"] == "be7e0b3fed136849f48ca6771eda8ca5"]

,contrato_id,dt_ref_portfolio,data_acao,tipo_acao,acao,status
8756,be7e0b3fed136849f48ca6771eda8ca5,2021-05-01,2021-05-03,HSM,campanhaobservacao,LIDO
36524,be7e0b3fed136849f48ca6771eda8ca5,2021-10-11,2021-10-11,EMAIL,campanhaobservacao,NAO ENTREGUE
62114,be7e0b3fed136849f48ca6771eda8ca5,2021-10-17,2021-10-19,HSM,campanhaparcelamento,ENTREGUE
69718,be7e0b3fed136849f48ca6771eda8ca5,2021-10-11,2021-10-11,HSM,campanhaobservacao,ENTREGUE
130244,be7e0b3fed136849f48ca6771eda8ca5,2021-04-21,2021-04-21,HSM,campanhaobservacao,NAO ENTREGUE
134490,be7e0b3fed136849f48ca6771eda8ca5,2021-10-02,2021-10-04,EMAIL,campanhaobservacao,ENTREGUE
168585,be7e0b3fed136849f48ca6771eda8ca5,2021-02-09,2021-02-09,HSM,campanhaobservacao,ENTREGUE
173471,be7e0b3fed136849f48ca6771eda8ca5,2021-02-09,2021-02-09,EMAIL,campanhaobservacao,ENTREGUE
251844,be7e0b3fed136849f48ca6771eda8ca5,2021-04-21,2021-04-21,EMAIL,campanhaobservacao,NAO ENTREGUE
359210,be7e0b3fed136849f48ca6771eda8ca5,2021-05-01,2021-05-03,EMAIL,campanhaobservacao,NAO ENTREGUE
365555,be7e0b3fed136849f48ca6771eda8ca5,2021-10-02,2021-10-04,HSM,campanhaobservacao,LIDO
398321,be7e0b3fed136849f48ca6771eda8ca5,2021-10-17,2021-10-19,EMAIL,campanhaparcelamento,ENTREGUE

In [23]:
geral = pd.read_csv("data/portfolio_geral.csv")
geral

,contrato_id,dt_ref_portfolio,safra,nr_documento,status_contrato,dt_contrato,dt_desembolso,dt_vencimento,dt_wo,prazo,...,juros_mes,juros_diario,perc_retencao,vlr_pgto_realizado,vlr_pgto_esperado,vlr_saldo_devedor,vlr_saldo_devedor_esperado,dsp,dspp,flag_transacao
0,356c02706c8e74b15004bb5964ade6bb,2022-03-01,2020-06,b0871d4e0d72afd1d44381e5b2453cb2,Settled,2020-06-24,2020-06-29,2020-12-24,2021-12-24,10.26,...,0.10788,0.00345,0.24000,0.0,163.00,0.55,0.00,0,0,0
1,1eb0e13f83f336146227ccc9efb08c47,2022-03-01,2020-07,938513461b4a4fcd2bf99ffd8f12b9be,Settled,2020-07-26,2020-07-28,2021-10-26,2022-10-26,25.65,...,0.04788,0.00157,0.08400,0.0,46.87,0.00,0.00,0,0,0
2,8b03675f597974ca96f06648e96af6d4,2022-03-01,2020-08,4303bd71ee3fe80aba4efc8dbd6c7d70,Settled,2020-08-13,2020-08-17,2022-02-13,2023-02-13,30.78,...,0.05388,0.00176,0.08076,0.0,45.57,0.00,0.00,0,0,0
3,4207c25cdd13aba5a05ae348e889d798,2022-03-01,2021-03,9c1dc4403f8a4833bd58eea3ee85c917,Active,2021-03-01,2021-03-03,2022-06-01,2023-06-01,25.65,...,0.04788,0.00157,0.19200,0.0,43.06,9469.47,461.96,20,82,0
4,7dfdca96b6ff0dd844e5e130aee88b30,2022-03-01,2020-11,3b6951df3075979c99a4dfd9f93efd38,Active,2020-10-31,2020-11-04,2022-01-31,2023-01-31,25.65,...,0.04788,0.00157,1.20000,0.0,200.09,57783.55,0.00,134,167,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8061001,b532ce3583bf083b58dcbb3156e9a6fb,2020-10-04,2020-09,66a443539af19dc890cafbebe0e1de8e,Active,2020-09-25,2020-09-29,2021-12-25,2022-12-25,25.65,...,0.05988,0.00195,0.18000,0.0,35.41,11201.47,11229.76,2,2,0
8061002,c5cce1cc49025572c7378279c1469923,2020-10-04,2020-05,f9d63ef575f20c5698146e2c796eedcd,Settled,2020-05-26,2020-05-29,2021-08-26,2022-08-26,25.65,...,0.03588,0.00118,0.30000,0.0,9.91,0.02,2756.18,0,0,0
8061003,67348b340a082aa77a67b7431cc91145,2020-10-31,2020-06,28283b4f3cc1654a879b64251f98164b,Active,2020-06-17,2020-06-23,2021-09-17,2022-09-17,25.65,...,0.07188,0.00233,0.10800,0.0,5.64,2064.82,1342.64,122,122,0
8061004,835d1f4def59389b5fbd64eaf195ece6,2020-09-14,2020-02,e45b288b207f5fce1707d6c8f3555aa2,Settled,2020-01-31,2020-02-05,2020-10-31,2021-10-31,13.68,...,0.07188,0.00233,0.24228,0.0,54.64,0.02,2350.90,0,0,1
8061005,e4753f517397dec57e638d49b982fc96,2020-10-17,2020-03,6cc7b4e91e82d38b829248fabda7f305,Settled,2020-03-03,2020-03-04,2021-03-03,2022-03-03,20.52,...,0.07788,0.00252,0.11844,0.0,34.75,0.29,4042.83,0,0,1

In [24]:
geral[geral["nr_documento"] == "01d6b0c45f3608d2d0fb8b7539c8769d"]

,contrato_id,dt_ref_portfolio,safra,nr_documento,status_contrato,dt_contrato,dt_desembolso,dt_vencimento,dt_wo,prazo,...,juros_mes,juros_diario,perc_retencao,vlr_pgto_realizado,vlr_pgto_esperado,vlr_saldo_devedor,vlr_saldo_devedor_esperado,dsp,dspp,flag_transacao
78559,be7e0b3fed136849f48ca6771eda8ca5,2022-01-29,2021-01,01d6b0c45f3608d2d0fb8b7539c8769d,Active,2021-01-21,2021-01-25,2022-04-21,2023-04-21,25.65,...,0.04788,0.00157,0.168,0.00,46.60,2611.10,756.18,1,1,1
89945,be7e0b3fed136849f48ca6771eda8ca5,2021-02-16,2021-01,01d6b0c45f3608d2d0fb8b7539c8769d,Active,2021-01-21,2021-01-25,2022-04-21,2023-04-21,25.65,...,0.04788,0.00157,0.168,0.00,46.99,15948.49,15279.34,4,22,1
172767,be7e0b3fed136849f48ca6771eda8ca5,2021-10-25,2021-01,01d6b0c45f3608d2d0fb8b7539c8769d,Active,2021-01-21,2021-01-25,2022-04-21,2023-04-21,25.65,...,0.04788,0.00157,0.168,41.16,46.99,11286.09,5249.94,0,38,1
186815,be7e0b3fed136849f48ca6771eda8ca5,2022-02-25,2021-01,01d6b0c45f3608d2d0fb8b7539c8769d,Active,2021-01-21,2021-01-25,2022-04-21,2023-04-21,25.65,...,0.04788,0.00157,0.168,75.19,46.60,445.66,0.00,0,0,1
186990,be7e0b3fed136849f48ca6771eda8ca5,2021-11-05,2021-01,01d6b0c45f3608d2d0fb8b7539c8769d,Active,2021-01-21,2021-01-25,2022-04-21,2023-04-21,25.65,...,0.04788,0.00157,0.168,57.46,46.99,10999.04,4736.05,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8022011,be7e0b3fed136849f48ca6771eda8ca5,2022-02-12,2021-01,01d6b0c45f3608d2d0fb8b7539c8769d,Active,2021-01-21,2021-01-25,2022-04-21,2023-04-21,25.65,...,0.04788,0.00157,0.168,0.00,46.60,1463.47,103.88,1,1,1
8025168,be7e0b3fed136849f48ca6771eda8ca5,2022-03-31,2021-01,01d6b0c45f3608d2d0fb8b7539c8769d,Settled,2021-01-21,2021-01-25,2022-04-21,2023-04-21,25.65,...,0.04788,0.00157,0.168,0.00,46.60,0.00,0.00,0,0,1
8026102,be7e0b3fed136849f48ca6771eda8ca5,2022-03-07,2021-01,01d6b0c45f3608d2d0fb8b7539c8769d,Settled,2021-01-21,2021-01-25,2022-04-21,2023-04-21,25.65,...,0.04788,0.00157,0.168,0.00,46.60,0.00,0.00,0,0,1
8026496,be7e0b3fed136849f48ca6771eda8ca5,2022-04-02,2021-01,01d6b0c45f3608d2d0fb8b7539c8769d,Settled,2021-01-21,2021-01-25,2022-04-21,2023-04-21,25.65,...,0.04788,0.00157,0.168,0.00,46.60,0.00,0.00,0,0,1
8026519,be7e0b3fed136849f48ca6771eda8ca5,2021-04-29,2021-01,01d6b0c45f3608d2d0fb8b7539c8769d,Active,2021-01-21,2021-01-25,2022-04-21,2023-04-21,25.65,...,0.04788,0.00157,0.168,16.72,46.99,15111.46,13283.10,0,13,1